### ISSUE TITLE
주문 쪽 디자인 수정

### ISSUE THREAD

**Issue by jae-ryong** [bone-stew/popmate-client#105]
## Feature Description
- 

## Todo list

- [x] 구매 상세에서 상품 라운드, 제목 크기, 상품 뭐 체크 되었는지 확인
- [x] 밑에 프래그먼트 글자크기
- [x] 구매 상세에서 글자크기, 간격
- [x] 뒤로가기 크기 다 같이 쓰는걸로
- [x] 주문상세바로가기 뒤로가기 했을때 (어려우면 확인 눌렀을때 메인으로)
- [x] 구매상세 ui 예약상세랑 맞춰서, qr버튼 동그랗게
