### ISSUE TITLE
QA 후 예약 로직 개선

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#106]
## Feature Description
- QA

## Todo list

- [x] 예약을 진행하지 않는 곳은 예약 버튼 비활성화
- [x] 다이얼로그 모서리 둥글게
- [x] 마이페이지 QR 로딩
- [x] 예약 성공 후 뒤로 가기 오류 
- [x] 예약 성공 후 마이페이지 예약 QR 코드 창으로 가기
