### ISSUE TITLE
예약 취소 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#115]
## Feature Description
- 예약 내역에서 예약을 취소할 수 있도록 한다.

## Todo list

- [ ] 예약 취소 다이얼로그를 구현한다.
- [ ] 예약 취소 API를 연동한다.
- [ ] 취소된 예약은 QR이 만료된 상태로 보여진다.
