### ISSUE TITLE
2차 QA

### ISSUE THREAD

**Issue by jae-ryong** [bone-stew/popmate-client#117]
## Feature Description
- 2차 디자인을 수정할 것이다.

## Todo list

- [x] 마이페이지 위아래 vertical wrap content
- [x] 상품 글자 마진
- [x] 제목 입장문구
- [x] 결제할때 화면 로딩
- [x] 결제 테스트기간 확인하기
