### ISSUE TITLE
팝업스토어 예약 페이지 구현

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#12]
## Feature Description
- 팝업스토어 예약 페이지와 예약 성공 다이얼로그를 구현한다

## Todo list

- [x] 팝업스토어 예약 페이지 그리기
- [x] 버튼 디자인
- [x] 버튼 이벤트 추가
- [x] 예약 승인시 성공 다이얼로그 추가
- [ ] 백엔드 API 연동
