### ISSUE TITLE
예약자 관련 API 변경에 따른 API 호출 및 응답 수정

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#141]
## Feature Description
- 예약자 관련 API에 버그로 인해 수정된 API 설계에 맞도록 수정한다.

## Todo list

- [x] 선착순 예약 성공 시 response에 필드 추가
- [x] 나의 예약 목록 조회시 response에 필드 추가
- [x] 나의 예약 목록의 어댑터에서 userReservationId를 넘기고 예약 상세 activity에서 변경된 API 호출
- [x] 예약 성공 시 받은 userReservationId를 예약 성공 다이얼로그로 넘기고 변경된 API 호출
- [x] 나의 예약 상세페이지에서 userReservationId를 다이얼로그로 넘겨서 변경된 예약 취소 API 호출
