### ISSUE TITLE
헤더를 공통으로 사용할 수 있도록 리팩토링

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#23]
## Feature Description
- 헤더를 공통으로 사용할 수 있도록 include를 사용하여 리팩토링한다.
- 제목은 각 레이아웃마다 동적으로 변경할 수 있도록 한다.

## Todo list

- [x] 헤더가 들어가는 layout.xml 생성
- [x] title이 레이아웃마다 동적으로 변경될 수 있도록 추가
- [x] 기존 레이아웃에 적용
