### ISSUE TITLE
디테일 페이지, 채팅 페이지 디자인 수정

### ISSUE THREAD

**Issue by WoowonKim** [bone-stew/popmate-client#65]
## Feature Description
- 디테일, 채팅 디자인 수정

## Todo list

- [x] 팝업 스토어 설명 약간 위로
- [x] 배너사진 약간 축소
- [x] 뒤로가기 위치 수정
- [x] 복사하기 이모티콘 수정
- [x] 팝업 프로모션 및 이벤트 위 아랴로 간격 넓게, 선색깔 연하게
- [x] 채팅방 입장하기에 붙이기
- [x] 채팅방 입장전에 로그인 다이얼로그
- [x] 메인 배너 밑에 있는 사진 (블러처리)
- [x] 채팅방 마진, 구분선을 입력한 색깔로
- [x] 채팅방 랜덤 닉네임
- [ ] 날짜 구분선
- [ ] 채팅 치면 바로 위에 올라가게
