### ISSUE TITLE
예약 버그 수정 및 디자인 변경

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#67]
## Feature Description
- 예약 버그 수정
- 디자인 통일

## Todo list

- [x] 뒤로 가기 적용
- [x] 글자 크기 통일
- [x] 나의 예약 정보에서 예약 인원 '명' 추가
- [ ] 시간순으로 정렬
- [x] 예약이 없을경우 예외 처리
- [x] 예약을 이미 한 경우에 마감되었습니다 -> 이미 예약하였습니다
- [x] 예약내역이 있는 경우에도 예약 내역 없음 textview가 뜨는 버그 수정
- [x] 이미 방문한 예약 내역은 방문 처리 표시
