### ISSUE TITLE
예약 예외 처리 및 디자인 수정

### ISSUE THREAD

**Issue by signature-hyeon** [bone-stew/popmate-client#76]
## Feature Description
- 예약 예외 처리 및 디자인 수정

## Todo list

- [x] 예약내역이 있는 경우에도 예약 내역 없음 textview가 뜨는 버그 수정
- [x] 예약을 진행하지 않는 팝업스토어에서 예약 버튼 눌렀을 경우 토스트 추가
- [x] 글자 크기 조정
- [x] 글자 색상 변경
- [ ] 예약 성공 다이얼로그의 확인 버튼 클릭 시 예약 내역으로 리다이렉트
- [x] 나의 예약 목록에서 날짜 포맷 변환
